apiVersion: apps/v1
kind: Deployment
metadata:
  name: apideployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api1
  template:
    metadata:
      labels:
        component: api1
    spec:
      containers:
        - name: api1
          image: muralialakuntla3/api2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MODE
              value: production
            - name: DB_HOST
              value: postgres-deployment
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_NAME
              value: postgres
            - name: DB_PASSWORD
              value: password
